# Generated by Django 4.2.1 on 2023-05-10 03:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='Ссылка на WhatsApp')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Ссылка на Telegram')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='MainPageDigits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients', models.IntegerField(default=0, verbose_name='Обслужено клиентов')),
                ('projects', models.IntegerField(default=0, verbose_name='Реализовано проектов')),
                ('hours_of_support', models.IntegerField(default=0, verbose_name='Часов поддержки')),
                ('hard_workers', models.IntegerField(default=0, verbose_name='Работников')),
            ],
            options={
                'verbose_name': 'Цифры на главной',
                'verbose_name_plural': 'Цифры на главной',
            },
        ),
        migrations.CreateModel(
            name='OurClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название компании')),
                ('logo', models.ImageField(upload_to='', verbose_name='Логотип компании')),
            ],
            options={
                'verbose_name': 'Наш клиент',
                'verbose_name_plural': 'Наши клиенты',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('client', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Клиент')),
                ('project_type', models.CharField(default='', max_length=255, verbose_name='Тип проекта')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Информация о проекте')),
                ('portfolio_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на проект')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение проекта')),
            ],
            options={
                'verbose_name': 'Портфолио',
                'verbose_name_plural': 'Портфолио',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Наименование услуги')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение услуги')),
                ('description', models.TextField(verbose_name='Описание')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Testimonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Имя')),
                ('company_models', models.CharField(default='', max_length=255, verbose_name='Наименование компании')),
                ('testimonal', models.TextField(verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Отзыв о нас',
                'verbose_name_plural': 'Отзывы о нас',
            },
        ),
    ]
