# Generated by Django 4.2.1 on 2023-05-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='long_description',
            field=models.TextField(default='', verbose_name='Подробное описание'),
        ),
    ]
