# Generated by Django 4.2 on 2023-04-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название компании')),
                ('logo', models.ImageField(upload_to='', verbose_name='Логотип компании')),
            ],
            options={
                'verbose_name': 'Наш клиент',
                'verbose_name_plural': 'Наши клиенты',
            },
        ),
    ]
