# Generated by Django 4.2.4 on 2023-08-30 07:21

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_service_long_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='long_description',
            field=tinymce.models.HTMLField(default='', verbose_name='Подробное описание'),
        ),
    ]
