# Generated by Django 4.2 on 2023-05-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_ourclients'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageDigits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients', models.IntegerField(default=0, verbose_name='Обслужено клиентов')),
                ('projects', models.IntegerField(default=0, verbose_name='Реализовано проектов')),
                ('hours_of_support', models.IntegerField(default=0, verbose_name='Часов поддержки')),
                ('hard_workers', models.IntegerField(default=0, verbose_name='Работников')),
            ],
            options={
                'verbose_name': 'Цифры на главной',
                'verbose_name_plural': 'Цифры на главной',
            },
        ),
        migrations.CreateModel(
            name='Testimonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Имя')),
                ('company_models', models.CharField(default='', max_length=255, verbose_name='Наименование компании')),
                ('testimonal', models.TextField(verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Отзыв о нас',
                'verbose_name_plural': 'Отзывы о нас',
            },
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_type',
            field=models.CharField(default='', max_length=255, verbose_name='Тип проекта'),
        ),
    ]
