# Generated by Django 4.2.1 on 2023-05-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_mainpagedigits_testimonal_portfolio_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='client',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на проект'),
        ),
    ]
