# Generated by Django 4.2.1 on 2023-05-09 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_portfolio_client_portfolio_portfolio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
